### ISSUE TITLE
multimarkdown version

### ISSUE THREAD

**Issue by ghost** [Zettelkasten-Method/zettelkasten.de#1]
`lib/filters/multimarkdown_filter.rb` calls the multimarkdown binary. Which version are you using locally so I can match on my machine. Thanks!

**Comment by DivineDominion** [comment]
My `mmd` reports v5.3.0. I don't rely on anything fancy in the 2 posts that still fall back to MultiMarkdown, so any version of peg-multimarkdown should just work.

**Comment by ghost** [comment]
thanks
