### ISSUE TITLE
data loss article

### ISSUE THREAD

**Issue by ghost** [Zettelkasten-Method/zettelkasten.de#5]
- [ ] discuss atom data loss
- [ ] how to think about protecting your notes
- [ ] how to setup a redundant backup solution
- [ ] how to version your files

**Comment by xHN35RQ** [comment]
assigned to @xhn35rq

**Comment by DivineDominion** [comment]
File versioning sounds fun. Do you have experience with non-programmers using Git or similar? 

Best thing I ever found was a designer suggesting you version file copies using file name suffixes:

* `A00` (first idea)
* `A01` (iteration on first idea)
* `B00` (second idea)
* `B01`
* `B` (final pick of that branch)

**Comment by ghost** [comment]
> Do you have experience with non-programmers using Git or similar?

Some. GUI apps help here.

> Best thing I ever found was a designer suggesting you version file copies using file name suffixes

cool idea, have a link?

**Comment by xHN35RQ** [comment]
> Best thing I ever found was a designer suggesting you version file copies using file name suffixes

cool idea, have a link?

**Comment by DivineDominion** [comment]
Wanted to say "no" at first, because I couldn't find it, but *facepalm* I do have a Zettelkasten! :)

http://holscher.wordpress.com/2012/11/28/going-paperless-file-naming-methodology/

**Comment by ghost** [comment]
My apologies, I won't have time to write this article. But perhaps someone else might be inspired to pick up the trail here. Thanks.
